title: Mon jardin à pensées numériques
description: >- # this means to ignore newlines until "baseurl:"
  Passionnée par les défis de l’apprentissage tout au long de la vie, j’essaie d’écouter pour mieux comprendre.
author: Gaëlle Bussière
email: bussiere.gl@gmail.com
instagram_username: bussieregaelle
github_username:  gaellebussiere

theme: minima

show_excerpts: true

plugins:
  - jekyll-feed